### ISSUE TITLE
Disable during testing

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.fingerpointing#100]
Is there a way to disable fingerpointing when running tests? Maybe with an environment variable or a setting in Python code?

Use case: I have a client package that has `collective.fingerpointing` in its `metadata.xml` dependency profiles, and does some tweaking of its settings. Test setup then fails:

```
$ bin/test -s zeelandia.theme
Running zeelandia.theme.testing.ZeelandiaThemeLayer:IntegrationTesting tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.332 seconds.
  Set up plone.app.testing.layers.PloneFixture in 10.812 seconds.
  Set up plone.app.event.testing.PAEventLayer in 0.877 seconds.
  Set up plone.app.contenttypes.testing.PloneAppContenttypes in 0.749 seconds.
  Set up zeelandia.theme.testing.ZeelandiaThemeLayer Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp27m/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 366, in run_layer
    setup_layer(options, layer, setup_layers)
  File "/Users/maurits/shared-eggs/cp27m/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 628, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/Users/maurits/shared-eggs/cp27m/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 633, in setup_layer
    layer.setUp()
  File "/Users/maurits/shared-eggs/cp27m/plone.app.testing-5.0.9-py2.7.egg/plone/app/testing/helpers.py", line 375, in setUp
    self.setUpPloneSite(portal)
  File "/Users/maurits/clients/zeelandia/plone5/develop/zeelandia.theme/src/zeelandia/theme/testing.py", line 44, in setUpPloneSite
    applyProfile(portal, 'zeelandia.theme:default')
  File "/Users/maurits/shared-eggs/cp27m/plone.app.testing-5.0.9-py2.7.egg/plone/app/testing/helpers.py", line 140, in applyProfile
    blacklisted_steps=blacklisted_steps)
  File "/Users/maurits/shared-eggs/cp27m/Products.GenericSetup-1.8.10-py2.7.egg/Products/GenericSetup/tool.py", line 388, in runAllImportStepsFromProfile
    dependency_strategy=dependency_strategy)
   - __traceback_info__: profile-zeelandia.theme:default
  File "/Users/maurits/shared-eggs/cp27m/Products.GenericSetup-1.8.10-py2.7.egg/Products/GenericSetup/tool.py", line 1469, in _runImportStepsFromContext
    message = self._doRunImportStep(step, context)
  File "/Users/maurits/shared-eggs/cp27m/Products.GenericSetup-1.8.10-py2.7.egg/Products/GenericSetup/tool.py", line 1281, in _doRunImportStep
    return handler(context)
   - __traceback_info__: plone.app.registry
  File "/Users/maurits/shared-eggs/cp27m/plone.app.registry-1.7.2-py2.7.egg/plone/app/registry/exportimport/handler.py", line 79, in importRegistry
    importer.importDocument(body)
   - __traceback_info__: registry/mosaic.xml
  File "/Users/maurits/shared-eggs/cp27m/plone.app.registry-1.7.2-py2.7.egg/plone/app/registry/exportimport/handler.py", line 127, in importDocument
    self.importRecords(node)
  File "/Users/maurits/shared-eggs/cp27m/plone.app.registry-1.7.2-py2.7.egg/plone/app/registry/exportimport/handler.py", line 414, in importRecords
    self.importRecord(field)
   - __traceback_info__: records name: plone.app.mosaic.interfaces.IFormat
  File "/Users/maurits/shared-eggs/cp27m/plone.app.registry-1.7.2-py2.7.egg/plone/app/registry/exportimport/handler.py", line 331, in importRecord
    existing_record.value = value
   - __traceback_info__: record name: plone.app.mosaic.formats.row_container_centered.name
  File "/Users/maurits/shared-eggs/cp27m/plone.registry-1.1.5-py2.7.egg/plone/registry/record.py", line 90, in _set_value
    notify(RecordModifiedEvent(self, oldValue, value))
  File "/Users/maurits/shared-eggs/cp27m/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/Users/maurits/shared-eggs/cp27m/zope.component-4.4.1-py2.7.egg/zope/component/event.py", line 27, in dispatch
    component_subscribers(event, None)
  File "/Users/maurits/shared-eggs/cp27m/zope.component-4.4.1-py2.7.egg/zope/component/_api.py", line 139, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/maurits/shared-eggs/cp27m/zope.interface-4.4.3-py2.7-macosx-10.12-x86_64.egg/zope/interface/registry.py", line 442, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/Users/maurits/shared-eggs/cp27m/zope.interface-4.4.3-py2.7-macosx-10.12-x86_64.egg/zope/interface/adapter.py", line 608, in subscribers
    subscription(*objects)
  File "/Users/maurits/shared-eggs/cp27m/collective.fingerpointing-1.8-py2.7.egg/collective/fingerpointing/subscribers/registry_logger.py", line 25, in registry_logger
    user, ip = get_request_information()
  File "/Users/maurits/shared-eggs/cp27m/collective.fingerpointing-1.8-py2.7.egg/collective/fingerpointing/utils.py", line 21, in get_request_information
    if 'HTTP_CF_CONNECTING_IP' in request.environ:
AttributeError: 'NoneType' object has no attribute 'environ'
```

Workaround may be to change `utils.get_request_information` to not fail when `getRequest() is None`. I do that now in a patch in my `testing.py`:

```
    def setUpZope(self, app, configurationContext):
        import collective.fingerpointing

        # Fix fingerpointing to not fail when there is no request,
        # else we cannot install the theme.
        from collective.fingerpointing import utils
        self._fp_get_request_information = utils.get_request_information

        def get_request_information():
            return ('None', 'None')
        utils.get_request_information = get_request_information

        self.loadZCML(package=collective.fingerpointing)
        self.loadZCML(package=zeelandia.theme)

    def tearDownZope(self, app):
        if hasattr(self, '_fp_get_request_information'):
            # Undo our patch.
            from collective.fingerpointing import utils
            utils.get_request_information = self._fp_get_request_information
```

That may be a fine change in `get_request_information` for real. The situation that there is no request probably mostly happens when running tests, but I can imagine that this also happens when you create a fresh Plone Site where you immediately install fingerpointing in the advanced Plone Site add form.  Or maybe when using `bin/instance run some-script.py`.

**Comment by hvelarde** [comment]
I think you can do the following in `get_request_information()`:

```python
request = getRequest()
if request is None:
    return (None, None)
```

**Comment by gbastien** [comment]
Hi @mauritsvanrees 

We fixed it in our tests like this : https://github.com/IMIO/Products.PloneMeeting/commit/76ff6706d1ae147aab02f1e6af126a0d70b611e5

But that would be better to have nothing to do ;-)

Gauthier

**Comment by idgserpro** [comment]
> We fixed it in our tests like this : [IMIO/Products.PloneMeeting@76ff670](https://github.com/IMIO/Products.PloneMeeting/commit/76ff6706d1ae147aab02f1e6af126a0d70b611e5)

Not related to this issue, but your solution just solved a different use case:

```
plone.api-1.8.5-py2.7.egg/plone/api/portal.py", line 427, in get_current_language
    return request.get('LANGUAGE', None) or \
AttributeError: 'NoneType' object has no attribute 'get'
```

Thanks!
