### ISSUE TITLE
No audit log file specified; audit log view is disabled.

### ISSUE THREAD

**Issue by almcg** [collective/collective.fingerpointing#95]
Running Plone 5, I have collective.fingerpointing installed. Summary of specific versions:

Plone 5.0.4
CMF 2.2.10
Zope 2.13.24
Python 2.7.5
PIL 3.1.1

All appeared to install correctly and I can activate the product via Site Setup, but when viewing the Audit Log (/@@fingerpointing-audit-log) I get the message "No audit log file specified; audit log view is disabled".

I have reviewed the documentation, specifically the note "If you didn’t specify a Finger Pointing audit log file name, you’ll see a warning". In buildout I have the following:

=============================================
zope-conf-additional +=
    <product-config collective.fingerpointing>
    audit-log /opt/plone/zinstance/var/log/audit.log
    audit-log-max-size 10240
    audit-log-old-files 30
    </product-config>
=============================================

Is there further configuration necessary to get the Audit Log enabled via /@@fingerpointing-audit-log?

**Comment by hvelarde** [comment]
are you including the trail spaces?

```ini
[instance]
zope-conf-additional +=
    <product-config collective.fingerpointing>
        audit-log ${buildout:directory}/var/log/audit.log
        audit-log-max-size 10485760
        audit-log-old-files 30
    </product-config>
```

**Comment by almcg** [comment]
Hi @hvelarde 

Thank you for the reply. We've double-checked and yes, the trail spaces are included.

The plugin appears to function correctly (I can access the settings via Site Setup) but the Audit Log only ever shows "No audit log file specified; audit log view is disabled".

**Comment by hvelarde** [comment]
I have no idea what's  going on then; we've been using this without any problem.

**Comment by ewohnlich** [comment]
I have the same problem in a Plone 5.2 environment. 

from config.py:
```
from App.config import getConfiguration
...
zopeConf = getConfiguration()
product_config = getattr(zopeConf, 'product_config', {})
```
_product_config_ is an empty dict. I'm not familiar with using zope-conf-additional so I'm not sure what else to look at in debugging. Should I expect this to have a counterpart generated in parts/plone/etc/zope.conf?

**Comment by ewohnlich** [comment]
First of all the answer to my above question appears to be yes, it should put this at the end of the conf file, so its absence suggests something is wrong with the recipe or configuration at this step. Dug around a bit in plone.recipe.zope2instance (6.5.1). Inspecting options.keys() in recipe.py I see _'zope-conf-additional +'_. Note the plus sign - aha!

Changing `+=` to just `=` works, although obviously this would make it override any other settings for zope-conf-additional. Perhaps this is a bug in plone.recipe.zope2instance?

**Comment by fulv** [comment]
To add to the last comment, re-running buildout when there is a `+=` in `zope-conf-additional` results in this error:

```
Traceback (most recent call last):
  File "/usr/local/plone-5.2/zeoserver/lib/python3.6/site-packages/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/usr/local/plone-5.2/zeoserver/lib/python3.6/site-packages/zc/buildout/buildout.py", line 670, in install
    )= self._read_installed_part_options()
  File "/usr/local/plone-5.2/zeoserver/lib/python3.6/site-packages/zc/buildout/buildout.py", line 969, in _read_installed_part_options
    sections = zc.buildout.configparser.parse(fp, old)
  File "/usr/local/plone-5.2/zeoserver/lib/python3.6/site-packages/zc/buildout/configparser.py", line 236, in parse
    raise e
zc.buildout.configparser.ParsingError: File contains parsing errors: /usr/local/plone-5.2/zeoserver/.installed.cfg
        [line 108]: 'zope-conf-additional + = <product-config collective.fingerpointing>\n'
        [line 175]: 'zope-conf-additional + = <product-config collective.fingerpointing>\n'
        [line 242]: 'zope-conf-additional + = <product-config collective.fingerpointing>\n'
```

**Note the space between the `+` and the `=`**.  So yes, I would say that there is likely a bug in plone.recipe.zope2instance.
(Removing the `.installed.cfg` file gets past this error, but the only way to successfully add the configuration to the zope.conf file is to remove the `+`.)
